### PR TITLE
Add tap handler

### PR DESCRIPTION
**Pull request by lucido-simon**
Hi !

This PR provides an abstraction over a tap interface. It implements the interface trait defined in #42. The code was heavily inspired by Amazon's firecracker tap implementation.

Depends on #42.

### CODE REVIEW

**Review by sameo — APPROVED** [review]

**Review by sameo — COMMENTED** [review]
The first 2 commits look fine. The virtio mmio device manager depends on the vm_device PR, which is under review.

**Comment by lucido-simon** [comment]
@sameo i've rebased onto main. FYI, the `feat: add interface trait` comes from #42.

**Review by sameo — COMMENTED** [review]
Please rebase that PR.
Also, please add a more verbose commit message. `add tap` is 7 characters away from being empty...

**Comment by lucido-simon** [comment]
@sameo Done

**Review by sameo — APPROVED** [review]

**Pull request merged**
